name: Post Weekly Wisdom to Slack

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *" # Runs every minute

jobs:
  post_wisdom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select wisdom
        id: wisdom
        run: |
          WISDOM=$(cat elm-wisdom.json)
          TOTAL_CARDS=$(echo $WISDOM | jq 'length')
          WEEK_NUM=$(date +%U | awk '{print $1 % '$TOTAL_CARDS'}')
          SELECTED=$(echo $WISDOM | jq '.['$WEEK_NUM']')
          TITLE=$(echo $SELECTED | jq -r '.title')
          CONTENT=$(echo $SELECTED | jq -r '.content')
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "CONTENT=$CONTENT" >> $GITHUB_ENV

      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.24
        with:
          payload: |
            {
              "text": ":owl: ${{ env.TITLE }} :owl: \n\n${{ env.CONTENT }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
